### ISSUE TITLE
The docker build process includes an extensive harvest process

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/europeana-cc-lod#7]
The docker build process for the crawler fires off an extensive harvest process that runs for quite a long time (and even failed for me in a first run). This is unexpected behavior for a regular build process. Is this part of the testing sequence? In that case it should be made optional or at least more clear what is going on or use a smaller test set.

**Comment by sdevalk** [comment]
@nfreire Can you take a look at this issue?

I can confirm Enno's finding: when building the image...

`docker-compose build --no-cache`

...the 'build stage' part of the Dockerfile starts harvesting the 'centsprenten' dataset. My guess is that the Maven build command...

`RUN mvn --quiet -e -f ./pom.xml clean assembly:assembly`

...also starts the tests, including the `crawlTest()` that crawls the centsprenten.

Perhaps a different Maven command would suffice, e.g.

`RUN mvn --quiet -e -f ./pom.xml clean compile assembly:single`

I also get the messages underneath when building the image:

* `WARNING: The junit-platform-surefire-provider has been deprecated and is scheduled to be removed in JUnit Platform 1.4. Please use the built-in support in Maven Surefire >= 2.22.0 instead`
* `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".`

**Comment by nfreire** [comment]
I changed the maven build, and now the test is skipped unless explicitly requested in the build command.

The dependency to junit-platform-surefire-provider was removed from the pom. Doing this was enough to stop both warnings.

**Comment by sdevalk** [comment]
Thanks! The build now indeed doesn't start the test anymore.

However, if I start a new crawl...

```
    docker-compose run --rm crawler /bin/bash ./crawler.sh \
        -dataset_uri http://data.bibliotheken.nl/id/dataset/rise-centsprenten \
        -output_file /opt/europeana_cc_lod_share/crawled/centsprenten.nt \
        -log_file run.log
```

...the messages underneath are outputted:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Is this something you can fix (or are they innocent messages)?

**Comment by nfreire** [comment]
The warning is harmless, but I've found out how to remove it

**Comment by sdevalk** [comment]
Perfect! The crawler now does not display the messages anymore 👍
