### ISSUE TITLE
improve the converter example with a working default

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/europeana-cc-lod#8]
I suggest to change the example for the converter so that it produces a real output as a follow on running the crawler example. The kb_schema.org should be changed to point to the default 'example.org´ graphs. 

And the example run command should point to example mapping file like this: 
docker exec -it converter /bin/bash /opt/converter/scripts/convert.sh --input-file /opt/europeana_cc_lod_share/crawled/centsprenten.nt --mapping-file /opt/converter/mappings/examples/kb_schema2edm.rq --output-dir /opt/europeana_cc_lod_share/converted

**Comment by sdevalk** [comment]
I've cleaned up the [examples a bit and added a reference to mapping file `kb_schema2edm.rq`](https://github.com/netwerk-digitaal-erfgoed/europeana-cc-lod/commit/a36fb6c0a328a76f3b0a631a2d257cb71713a430) so that the examples actually work.
