### ISSUE TITLE
add an instruction to copy to result edm file to the host environment

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/europeana-cc-lod#9]
The current setup results in creating an output file on a shared docker volume. It will be unclear to the average user how to access the resultfile for further processing f.e. upload to the Europeana ingest environment. 

Add something like:
docker cp converter: converter:/opt/europeana_cc_lod_share/converter/centsprenten_edm_000001.ttl . 
Or consider using a fix mounted directory from the host (like ./data?).

**Comment by sdevalk** [comment]
I've added an [instruction to the README](https://github.com/netwerk-digitaal-erfgoed/europeana-cc-lod/commit/e9402c482c930852f39fc6f5a07668b67ccfedac) for getting the converted files.

Using a bind mount is definitely an option, although the [Docker documentation recommends volumes](https://docs.docker.com/storage/volumes/), e.g. for sharing data among containers.
